dist: trusty
sudo: required
language: python
env:
  global:
  - secure: KDdeOAyNvMm3rzCxs7f8F9bxmmbve4rB6arB4ZYrwleXzNR0lE/sEFF5bSiggryZRES+dWAZNtV/McgY/a7vVHlcKREo7fErb2g3NGvOgTjdPGu3IyQgtQXliuP0xK2D/uUZP8hCZAD6RpgNu7i+cBKotOMc2/96DfgXKJK1n8TWRlsbH95GcpMkUPDaWeonYrhRbCh7bXd5wNSL+FNN5MRvg3AEm6pJTJeoFtN92Rz4fruAiYwkhSkSBqkfjh/4bpIYccI37luuYpNTM0VYxFDBsOEERxUe/qpkiJZQtxV1m2lylJhSEcarSYO1AzGOmoLq5mBXDMDC11k6kbzXSZ75lDTfjaROw/P4MZlsFLuzTNJr8DkmwsnPZnXl20G+P3QyJCOjFxULuNa4lrpj38WO0XXh49StOdFNbjkNHUbOv8GpEFLYSRFdQc5vMcJ6cPgHDTLNsqxqIB3QdHfUWdl5WQO6wyARfP3aT1C5QREyj7EchqCmCDk9XZ6wxRfwsvl+zOIisKB/iL3hkeuo3duRwBAUgVMBYhs0ad3skMA7AcDd1DDhGEyicA9AGGMO48ZFFLMhTV2NocLd3uyaZDEumnad2HSsoJYz/eZaSnbvcqM86MwIxOivchsY2QdvIdl2gKSBBAzpfaXTOr/RbOy8vfei35IuTnVqUXsBAuI=
  - secure: w4+1aPeH9bA2GHVlYnRhDRsalQN/GA8bfujmfBsMK58AJ7x+Wz73MVHpG3BdtTaKkk9iBlkzVCnaY+QgG0HZfG6lili26vSE7ECh8L6SbgRK0M1Qs36bIic7LBfYWHkM9A2gwyyuhU0KlMMygxb2n4J/SMmQ6gkGnxwQTB693n9d9M965niRhaLQNXKHyp6mHOqlmYVK256J8UlEJQXV3MUElzYw6DWLjz/l8w+5+hs1pf7dsbg7yB+xjoffTXgLcaUW0/hq7VbuTCtlrMqV5ltP01ZP2DrB/xMG9q2j5MDyd0OfdN03AsdeFW20rA6UQTE7D8WRyDeiB+SDrDy5+vi3aRvYvbFoDtVlu0iOwWpI8qsfOjX6BCOuccXUNXbReRbz9b9/MEeX3ep+1N5cfTscv3TqRTQiaYfL0isvWZ2Pku9aMrQJg/7FIHEQTNQgG3QYl7tl0Mq8lRTt8CXNEHBzXpmZozYKzLY1uuJY2Bo5QZGGqMd1mQ/AegDeldlLg6zWEMABY0BgnEU4SHGN5FIOzyQTe5jSAJSrO6/uo4ycXWJJROj1KC4H1BftSvS5j0fir3migHO3Uc/RVbelO1/TyVOxy1ak/l/HO7rEHLz9gHI5f+rjcB/xHo55YQZqSiDNX8l2CjJEyCTiDL0y7Lo+KWoA1ukjU1HR+SuZstk=
python:
- 3.6
services:
- docker
before_install:
- docker pull budgetkey/budgetkey-data-pipelines:latest
- docker build --cache-from budgetkey/budgetkey-data-pipelines:latest -t budgetkey/budgetkey-data-pipelines:latest .
install:
- sudo apt-get install libleveldb-dev libleveldb1
before_script:
- make install
script:
- make test
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
